### ISSUE TITLE
Practica Reconocimiento de Imagenes

### ISSUE THREAD

**Issue by hiuta** [SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-joel#2]
[Reporte Reconocimiento de Imagenes con RA.pdf](https://github.com/SistemasTecTlaxiaco/reconocimiento-de-imagenes-con-ra-equipo-joel/files/6475323/Reporte.Reconocimiento.de.Imagenes.con.RA.pdf)

**Comment by ObedG** [comment]
Calificación : 19

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
